<?php

namespace App\Models;

use App\Traits\HasRecordOwnerProperties;
use Illuminate\Database\Eloquent\Model as Model;

class GeneralSettings extends Model
{
    use HasRecordOwnerProperties;

    /**
     * @var string
     */
    protected $table = 'general_settings';

    /**
     * @var string[]
     */
    protected $fillable = [
        'physical_products_system',
        'digital_products_system',
        'marketplace_system',
        'classified_ads_system',
        'bidding_system',
        'selling_license_keys_system',
        'multi_vendor_system',
        'membership_plans_system',
        'vat_status',
        'site_lang',
        'timezone',
        'application_name',
        'selected_navigation',
        'menu_limit',
        'recaptcha_site_key',
        'recaptcha_secret_key',
        'recaptcha_lang',
        'custom_css_codes',
        'custom_javascript_codes',
        'mail_library',
        'mail_protocol',
        'mail_encryption',
        'mail_host',
        'mail_port',
        'mail_username',
        'mail_password',
        'mail_title',
        'mail_reply_to',
        'email_verification',
        'facebook_app_id',
        'facebook_app_secret',
        'google_client_id',
        'google_client_secret',
        'vk_app_id',
        'vk_secure_key',
        'google_analytics',
        'promoted_products',
        'multilingual_system',
        'product_comments',
        'comment_approval_system',
        'reviews',
        'blog_comments',
        'slider_status',
        'slider_type',
        'slider_effect',
        'featured_categories',
        'index_promoted_products',
        'index_promoted_products_count',
        'index_latest_products',
        'index_latest_products_count',
        'index_blog_slider',
        'product_link_structure',
        'mds_key',
        'purchase_code',
        'site_color',
        'logo',
        'logo_email',
        'favicon',
        'watermark_image_large',
        'watermark_image_mid',
        'watermark_image_small',
        'watermark_vrt_alignment',
        'watermark_hor_alignment',
        'watermark_product_images',
        'watermark_blog_images',
        'watermark_thumbnail_images',
        'facebook_comment',
        'facebook_comment_status',
        'product_cache_system',
        'static_content_cache_system',
        'refresh_cache_database_changes',
        'cache_refresh_time',
        'rss_system',
        'approve_before_publishing',
        'commission_rate',
        'send_email_new_product',
        'send_email_buyer_purchase',
        'send_email_contact_messages',
        'send_email_order_shipped',
        'send_email_shop_opening_request',
        'send_email_bidding_system',
        'mail_options_account',
        'vendor_verification_system',
        'hide_vendor_contact_information',
        'guest_checkout',
        'maintenance_mode_title',
        'maintenance_mode_description',
        'maintenance_mode_status',
        'max_file_size_image',
        'max_file_size_video',
        'max_file_size_audio',
        'google_adsense_code',
        'sort_categories',
        'sort_parent_categories_by_order',
        'pwa_status',
        'location_search_header',
        'vendor_bulk_product_upload',
        'show_sold_products',
        'newsletter_status',
        'newsletter_popup',
        'request_documents_vendors',
        'explanation_documents_vendors',
        'last_cron_update',
        'last_cron_update_long',
        'version',
        'is_active',
        'created_at',
        'updated_at',
        'added_by',
        'updated_by',
    ];

    /**
     * @var string[]
     */
    protected $casts = [
        'physical_products_system' => 'integer',
        'digital_products_system' => 'integer',
        'marketplace_system' => 'integer',
        'classified_ads_system' => 'integer',
        'bidding_system' => 'integer',
        'selling_license_keys_system' => 'integer',
        'multi_vendor_system' => 'integer',
        'membership_plans_system' => 'integer',
        'vat_status' => 'integer',
        'site_lang' => 'integer',
        'timezone' => 'string',
        'application_name' => 'string',
        'selected_navigation' => 'integer',
        'menu_limit' => 'integer',
        'recaptcha_site_key' => 'string',
        'recaptcha_secret_key' => 'string',
        'recaptcha_lang' => 'string',
        'custom_css_codes' => 'string',
        'custom_javascript_codes' => 'string',
        'mail_library' => 'string',
        'mail_protocol' => 'string',
        'mail_encryption' => 'string',
        'mail_host' => 'string',
        'mail_port' => 'string',
        'mail_username' => 'string',
        'mail_password' => 'string',
        'mail_title' => 'string',
        'mail_reply_to' => 'string',
        'email_verification' => 'integer',
        'facebook_app_id' => 'string',
        'facebook_app_secret' => 'string',
        'google_client_id' => 'string',
        'google_client_secret' => 'string',
        'vk_app_id' => 'string',
        'vk_secure_key' => 'string',
        'google_analytics' => 'string',
        'promoted_products' => 'integer',
        'multilingual_system' => 'integer',
        'product_comments' => 'integer',
        'comment_approval_system' => 'integer',
        'reviews' => 'integer',
        'blog_comments' => 'integer',
        'slider_status' => 'integer',
        'slider_type' => 'string',
        'slider_effect' => 'string',
        'featured_categories' => 'integer',
        'index_promoted_products' => 'integer',
        'index_promoted_products_count' => 'integer',
        'index_latest_products' => 'integer',
        'index_latest_products_count' => 'integer',
        'index_blog_slider' => 'integer',
        'product_link_structure' => 'string',
        'mds_key' => 'string',
        'purchase_code' => 'string',
        'site_color' => 'string',
        'logo' => 'string',
        'logo_email' => 'string',
        'favicon' => 'string',
        'watermark_image_large' => 'string',
        'watermark_image_mid' => 'string',
        'watermark_image_small' => 'string',
        'watermark_vrt_alignment' => 'string',
        'watermark_hor_alignment' => 'string',
        'watermark_product_images' => 'integer',
        'watermark_blog_images' => 'integer',
        'watermark_thumbnail_images' => 'integer',
        'facebook_comment' => 'string',
        'facebook_comment_status' => 'integer',
        'product_cache_system' => 'integer',
        'static_content_cache_system' => 'integer',
        'refresh_cache_database_changes' => 'integer',
        'cache_refresh_time' => 'integer',
        'rss_system' => 'integer',
        'approve_before_publishing' => 'integer',
        'commission_rate' => 'integer',
        'send_email_new_product' => 'integer',
        'send_email_buyer_purchase' => 'integer',
        'send_email_contact_messages' => 'integer',
        'send_email_order_shipped' => 'integer',
        'send_email_shop_opening_request' => 'integer',
        'send_email_bidding_system' => 'integer',
        'mail_options_account' => 'string',
        'vendor_verification_system' => 'integer',
        'hide_vendor_contact_information' => 'integer',
        'guest_checkout' => 'integer',
        'maintenance_mode_title' => 'string',
        'maintenance_mode_description' => 'string',
        'maintenance_mode_status' => 'integer',
        'max_file_size_image' => 'integer',
        'max_file_size_video' => 'integer',
        'max_file_size_audio' => 'integer',
        'google_adsense_code' => 'string',
        'sort_categories' => 'string',
        'sort_parent_categories_by_order' => 'integer',
        'pwa_status' => 'integer',
        'location_search_header' => 'integer',
        'vendor_bulk_product_upload' => 'integer',
        'show_sold_products' => 'integer',
        'newsletter_status' => 'integer',
        'newsletter_popup' => 'integer',
        'request_documents_vendors' => 'integer',
        'explanation_documents_vendors' => 'string',
        'last_cron_update' => 'datetime',
        'last_cron_update_long' => 'datetime',
        'version' => 'string',
        'is_active' => 'boolean',
        'added_by' => 'integer',
        'updated_by' => 'integer',
    ];
}
