<?php

namespace App\Http\Resources\Device;

use App\Http\Resources\BaseAPIResource;
use Illuminate\Http\Request;

class GeneralSettingsResource extends BaseAPIResource
{
    /**
     * @param Request $request
     *
     * @return array
     */
    public function toArray($request): array
    {
        $fieldsFilter = $request->get('fields');
        if (!empty($fieldsFilter) || $request->get('include')) {
            return $this->resource->toArray();
        }

        return [
            'id' => $this->id,
            'physical_products_system' => $this->physical_products_system,
            'digital_products_system' => $this->digital_products_system,
            'marketplace_system' => $this->marketplace_system,
            'classified_ads_system' => $this->classified_ads_system,
            'bidding_system' => $this->bidding_system,
            'selling_license_keys_system' => $this->selling_license_keys_system,
            'multi_vendor_system' => $this->multi_vendor_system,
            'membership_plans_system' => $this->membership_plans_system,
            'vat_status' => $this->vat_status,
            'site_lang' => $this->site_lang,
            'timezone' => $this->timezone,
            'application_name' => $this->application_name,
            'selected_navigation' => $this->selected_navigation,
            'menu_limit' => $this->menu_limit,
            'recaptcha_site_key' => $this->recaptcha_site_key,
            'recaptcha_secret_key' => $this->recaptcha_secret_key,
            'recaptcha_lang' => $this->recaptcha_lang,
            'custom_css_codes' => $this->custom_css_codes,
            'custom_javascript_codes' => $this->custom_javascript_codes,
            'mail_library' => $this->mail_library,
            'mail_protocol' => $this->mail_protocol,
            'mail_encryption' => $this->mail_encryption,
            'mail_host' => $this->mail_host,
            'mail_port' => $this->mail_port,
            'mail_username' => $this->mail_username,
            'mail_password' => $this->mail_password,
            'mail_title' => $this->mail_title,
            'mail_reply_to' => $this->mail_reply_to,
            'email_verification' => $this->email_verification,
            'facebook_app_id' => $this->facebook_app_id,
            'facebook_app_secret' => $this->facebook_app_secret,
            'google_client_id' => $this->google_client_id,
            'google_client_secret' => $this->google_client_secret,
            'vk_app_id' => $this->vk_app_id,
            'vk_secure_key' => $this->vk_secure_key,
            'google_analytics' => $this->google_analytics,
            'promoted_products' => $this->promoted_products,
            'multilingual_system' => $this->multilingual_system,
            'product_comments' => $this->product_comments,
            'comment_approval_system' => $this->comment_approval_system,
            'reviews' => $this->reviews,
            'blog_comments' => $this->blog_comments,
            'slider_status' => $this->slider_status,
            'slider_type' => $this->slider_type,
            'slider_effect' => $this->slider_effect,
            'featured_categories' => $this->featured_categories,
            'index_promoted_products' => $this->index_promoted_products,
            'index_promoted_products_count' => $this->index_promoted_products_count,
            'index_latest_products' => $this->index_latest_products,
            'index_latest_products_count' => $this->index_latest_products_count,
            'index_blog_slider' => $this->index_blog_slider,
            'product_link_structure' => $this->product_link_structure,
            'mds_key' => $this->mds_key,
            'purchase_code' => $this->purchase_code,
            'site_color' => $this->site_color,
            'logo' => $this->logo,
            'logo_email' => $this->logo_email,
            'favicon' => $this->favicon,
            'watermark_image_large' => $this->watermark_image_large,
            'watermark_image_mid' => $this->watermark_image_mid,
            'watermark_image_small' => $this->watermark_image_small,
            'watermark_vrt_alignment' => $this->watermark_vrt_alignment,
            'watermark_hor_alignment' => $this->watermark_hor_alignment,
            'watermark_product_images' => $this->watermark_product_images,
            'watermark_blog_images' => $this->watermark_blog_images,
            'watermark_thumbnail_images' => $this->watermark_thumbnail_images,
            'facebook_comment' => $this->facebook_comment,
            'facebook_comment_status' => $this->facebook_comment_status,
            'product_cache_system' => $this->product_cache_system,
            'static_content_cache_system' => $this->static_content_cache_system,
            'refresh_cache_database_changes' => $this->refresh_cache_database_changes,
            'cache_refresh_time' => $this->cache_refresh_time,
            'rss_system' => $this->rss_system,
            'approve_before_publishing' => $this->approve_before_publishing,
            'commission_rate' => $this->commission_rate,
            'send_email_new_product' => $this->send_email_new_product,
            'send_email_buyer_purchase' => $this->send_email_buyer_purchase,
            'send_email_contact_messages' => $this->send_email_contact_messages,
            'send_email_order_shipped' => $this->send_email_order_shipped,
            'send_email_shop_opening_request' => $this->send_email_shop_opening_request,
            'send_email_bidding_system' => $this->send_email_bidding_system,
            'mail_options_account' => $this->mail_options_account,
            'vendor_verification_system' => $this->vendor_verification_system,
            'hide_vendor_contact_information' => $this->hide_vendor_contact_information,
            'guest_checkout' => $this->guest_checkout,
            'maintenance_mode_title' => $this->maintenance_mode_title,
            'maintenance_mode_description' => $this->maintenance_mode_description,
            'maintenance_mode_status' => $this->maintenance_mode_status,
            'max_file_size_image' => $this->max_file_size_image,
            'max_file_size_video' => $this->max_file_size_video,
            'max_file_size_audio' => $this->max_file_size_audio,
            'google_adsense_code' => $this->google_adsense_code,
            'sort_categories' => $this->sort_categories,
            'sort_parent_categories_by_order' => $this->sort_parent_categories_by_order,
            'pwa_status' => $this->pwa_status,
            'location_search_header' => $this->location_search_header,
            'vendor_bulk_product_upload' => $this->vendor_bulk_product_upload,
            'show_sold_products' => $this->show_sold_products,
            'newsletter_status' => $this->newsletter_status,
            'newsletter_popup' => $this->newsletter_popup,
            'request_documents_vendors' => $this->request_documents_vendors,
            'explanation_documents_vendors' => $this->explanation_documents_vendors,
            'last_cron_update' => $this->last_cron_update,
            'last_cron_update_long' => $this->last_cron_update_long,
            'version' => $this->version,
            'is_active' => $this->is_active,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'added_by' => $this->added_by,
            'updated_by' => $this->updated_by,
        ];
    }
}
